project:
  buildStatus: ready
  external: false
  provider: github
  deployment:
    builds:
      master:
        weight: 1
        id: _dcqnjp279
        environmentVariables: []
        branch: master
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
    contentDirectory:
      - src/content
    buildCommand: gatsby build
  type: gatsby
  status: active
  name: jmolivas/gatsby-casper
schemas:
  - type: form
    definitions:
      fields:
        - required: false
          type: string
          id: name
          widget: text
          name: Name
        - id: message
          widget: textarea
          name: Message
          required: false
          type: string
      schema:
        id: contact
        name: Contact
    schema:
      json:
        required: []
        type: object
        properties:
          name:
            default: ''
            type: string
            title: Name
          message:
            title: Message
            default: ''
            type: string
      name: Contact
      ui:
        name:
          'ui:widget': text
        'ui:order':
          - name
          - message
          - '*'
        message:
          'ui:widget': textarea
  - type: content
    definitions:
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Title
          type: string
          required: true
          value: ''
          id: title
        - type: string
          required: false
          value: ''
          id: excerpt
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Excerpt
        - type: string
          required: true
          value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
          name: Content
        - system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
        - type: string
          required: true
          value: ''
          id: date
          orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
        - system: false
          widget: text
          name: Author
          type: string
          required: true
          value: ''
          id: author
          orderable: true
          removable: true
        - required: false
          type: string
          id: tags
          widget: collection
          name: Tags
        - id: draft
          widget: checkbox
          name: Draft
          required: false
          type: boolean
      schema:
        id: page
        name: Page
    schema:
      json:
        required:
          - title
          - content
          - image
          - date
          - author
        type: object
        properties:
          author:
            title: Author
            default: ''
            type: string
          excerpt:
            title: Excerpt
            default: ''
            type: string
          image:
            title: Image
            default: ''
            type: string
          content:
            title: Content
            default: ''
            type: string
          date:
            title: Date
            default: ''
            type: string
          tags:
            default: ''
            type: string
            title: Tags
          draft:
            default: ''
            type: boolean
            title: Draft
          title:
            default: ''
            type: string
            title: Title
      name: Page
      ui:
        author:
          'ui:widget': text
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - tags
          - draft
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        tags:
          'ui:widget': collection
        draft:
          'ui:widget': checkbox
        title:
          'ui:widget': text
  - type: dataset
    definitions:
      fields:
        - value: ''
          id: id
          orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
        - orderable: true
          removable: true
          system: false
          widget: textarea
          name: Description
          type: string
          required: true
          value: ''
          id: description
        - type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Image
      schema:
        name: Tag
        id: tag
    schema:
      ui:
        id:
          'ui:widget': text
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - id
          - description
          - image
          - '*'
        description:
          'ui:widget': textarea
      json:
        required:
          - id
          - description
          - image
        type: object
        properties:
          id:
            title: Id
            default: ''
            type: string
          image:
            default: ''
            type: string
            title: Image
          description:
            default: ''
            type: string
            title: Description
      name: Tag
  - type: dataset
    definitions:
      schema:
        name: Author
        id: author
      fields:
        - widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
          orderable: true
          removable: true
          system: false
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Avatar
          type: string
          required: true
          value: ''
          id: avatar
        - system: false
          widget: textarea
          name: Bio
          type: string
          required: true
          value: ''
          id: bio
          orderable: true
          removable: true
        - type: string
          required: true
          value: ''
          id: facebook
          orderable: true
          removable: true
          system: false
          widget: text
          name: Facebook
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Location
          type: string
          required: true
          value: ''
          id: location
        - removable: true
          system: false
          widget: MediaSchema
          name: Profile_image
          type: string
          required: true
          value: ''
          id: profile_image
          orderable: true
        - name: Twiter
          type: string
          required: true
          value: ''
          id: twiter
          orderable: true
          removable: true
          system: false
          widget: text
        - name: Twitter
          type: string
          required: true
          value: ''
          id: twitter
          orderable: true
          removable: true
          system: false
          widget: text
        - removable: true
          system: false
          widget: text
          name: Website
          type: string
          required: true
          value: ''
          id: website
          orderable: true
    schema:
      json:
        properties:
          twiter:
            title: Twiter
            default: ''
            type: string
          website:
            title: Website
            default: ''
            type: string
          twitter:
            default: ''
            type: string
            title: Twitter
          facebook:
            default: ''
            type: string
            title: Facebook
          bio:
            title: Bio
            default: ''
            type: string
          profile_image:
            title: Profile_image
            default: ''
            type: string
          avatar:
            title: Avatar
            default: ''
            type: string
          id:
            default: ''
            type: string
            title: Id
          location:
            title: Location
            default: ''
            type: string
        required:
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
        type: object
      name: Author
      ui:
        location:
          'ui:widget': text
        twiter:
          'ui:widget': text
        website:
          'ui:widget': text
        twitter:
          'ui:widget': text
        facebook:
          'ui:widget': text
        bio:
          'ui:widget': textarea
        'ui:order':
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
          - '*'
        profile_image:
          'ui:widget': MediaSchema
        avatar:
          'ui:widget': MediaSchema
        id:
          'ui:widget': text
mapping:
  content:
    - schema: page
      path: src/content/google-spreadsheet-manage-content.md
    - schema: page
      path: src/content/welcome.md
    - schema: page
      path: src/content/using-gatsby.md
    - schema: page
      path: src/content/great-catsby.md
    - schema: page
      path: src/content/gatsby-wax.md
    - schema: page
      path: src/content/how-run-puppeteer-headless-chrome.md
    - schema: page
      path: src/content/a-full-style-test.md
  dataset:
    - schema: tag
      path: src/content/tag.yaml
    - schema: author
      path: src/content/author.yaml
  form: []
