project:
  buildStatus: ready
  external: false
  provider: github
  deployment:
    contentDirectory:
      - src/content
    buildCommand: gatsby build
    builds:
      master:
        branch: master
        weight: 1
        id: _dcqnjp279
        environmentVariables: []
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
  type: gatsby
  status: active
  name: jmolivas/gatsby-casper
schemas:
  - definitions:
      fields:
        - value: ''
          id: id
          orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
        - value: ''
          id: description
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Description
          type: string
          required: true
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
      schema:
        id: tag
        name: Tag
    schema:
      json:
        properties:
          description:
            title: Description
            default: ''
            type: string
          id:
            default: ''
            type: string
            title: Id
          image:
            default: ''
            type: string
            title: Image
        required:
          - id
          - description
          - image
        type: object
      name: Tag
      ui:
        'ui:order':
          - id
          - description
          - image
          - '*'
        description:
          'ui:widget': textarea
        id:
          'ui:widget': text
        image:
          'ui:widget': MediaSchema
    type: dataset
  - definitions:
      fields:
        - value: ''
          id: title
          orderable: true
          removable: true
          system: false
          widget: text
          name: Title
          type: string
          required: true
        - widget: textarea
          name: Excerpt
          type: string
          required: false
          value: ''
          id: excerpt
          orderable: true
          removable: true
          system: false
        - widget: SlateEditor
          name: Content
          type: string
          required: true
          value: ''
          id: content
          orderable: true
          removable: true
          system: false
        - removable: true
          system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
        - orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
          value: ''
          id: date
        - value: ''
          id: author
          orderable: true
          removable: true
          system: false
          widget: text
          name: Author
          type: string
          required: true
        - widget: collection
          name: Tags
          required: false
          type: string
          id: tags
        - id: draft
          widget: checkbox
          name: Draft
          required: false
          type: boolean
      schema:
        id: page
        name: Page
    schema:
      json:
        required:
          - title
          - content
          - image
          - date
          - author
        type: object
        properties:
          author:
            default: ''
            type: string
            title: Author
          excerpt:
            title: Excerpt
            default: ''
            type: string
          image:
            title: Image
            default: ''
            type: string
          content:
            default: ''
            type: string
            title: Content
          date:
            default: ''
            type: string
            title: Date
          tags:
            title: Tags
            default: ''
            type: string
          draft:
            title: Draft
            default: ''
            type: boolean
          title:
            title: Title
            default: ''
            type: string
      name: Page
      ui:
        author:
          'ui:widget': text
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - tags
          - draft
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        tags:
          'ui:widget': collection
        draft:
          'ui:widget': checkbox
        title:
          'ui:widget': text
    type: content
  - type: form
    definitions:
      schema:
        id: contact
        name: Contact
      fields:
        - id: name
          widget: text
          name: Name
          required: false
          type: string
        - widget: textarea
          name: Message
          required: false
          type: string
          id: message
    schema:
      json:
        required: []
        type: object
        properties:
          message:
            title: Message
            default: ''
            type: string
          name:
            title: Name
            default: ''
            type: string
      name: Contact
      ui:
        message:
          'ui:widget': textarea
        name:
          'ui:widget': text
        'ui:order':
          - name
          - message
          - '*'
  - definitions:
      fields:
        - value: ''
          id: id
          orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
        - value: ''
          id: avatar
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Avatar
          type: string
          required: true
        - removable: true
          system: false
          widget: textarea
          name: Bio
          type: string
          required: true
          value: ''
          id: bio
          orderable: true
        - name: Facebook
          type: string
          required: true
          value: ''
          id: facebook
          orderable: true
          removable: true
          system: false
          widget: text
        - widget: text
          name: Location
          type: string
          required: true
          value: ''
          id: location
          orderable: true
          removable: true
          system: false
        - removable: true
          system: false
          widget: MediaSchema
          name: Profile_image
          type: string
          required: true
          value: ''
          id: profile_image
          orderable: true
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Twiter
          type: string
          required: true
          value: ''
          id: twiter
        - name: Twitter
          type: string
          required: true
          value: ''
          id: twitter
          orderable: true
          removable: true
          system: false
          widget: text
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Website
          type: string
          required: true
          value: ''
          id: website
      schema:
        name: Author
        id: author
    schema:
      json:
        required:
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
        type: object
        properties:
          website:
            default: ''
            type: string
            title: Website
          twitter:
            default: ''
            type: string
            title: Twitter
          facebook:
            default: ''
            type: string
            title: Facebook
          bio:
            title: Bio
            default: ''
            type: string
          profile_image:
            default: ''
            type: string
            title: Profile_image
          avatar:
            default: ''
            type: string
            title: Avatar
          id:
            title: Id
            default: ''
            type: string
          location:
            title: Location
            default: ''
            type: string
          twiter:
            default: ''
            type: string
            title: Twiter
      name: Author
      ui:
        avatar:
          'ui:widget': MediaSchema
        id:
          'ui:widget': text
        location:
          'ui:widget': text
        twiter:
          'ui:widget': text
        website:
          'ui:widget': text
        twitter:
          'ui:widget': text
        facebook:
          'ui:widget': text
        bio:
          'ui:widget': textarea
        'ui:order':
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
          - '*'
        profile_image:
          'ui:widget': MediaSchema
    type: dataset
mapping:
  content:
    - schema: page
      path: src/content/welcome.md
    - schema: page
      path: src/content/using-gatsby.md
    - schema: page
      path: src/content/a-full-style-test.md
    - schema: page
      path: src/content/great-catsby.md
    - schema: page
      path: src/content/how-run-puppeteer-headless-chrome.md
    - schema: page
      path: src/content/google-spreadsheet-manage-content.md
    - schema: page
      path: src/content/gatsby-wax.md
  dataset:
    - schema: author
      path: src/content/author.yaml
    - schema: tag
      path: src/content/tag.yaml
  form: []
